<?php

namespace App\Http\Requests\Logistics;

use App\Rules\SelectableUnit;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreMaterialRequest extends FormRequest
{
    /** Route-level `role:LOGISTICS` middleware already gates this action (PRD §7.1 "Material – Master": LOG CRUD). */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * `stock` is deliberately absent — it only changes through stock
     * in/out (StockService), so every unit has a ledger row behind it.
     * The item is a structured identity (Sprint 11 §5.5 Lapis 1): the
     * display name and code are generated by MaterialCatalogService, which
     * also refuses an existing item and wants `similar_reason` when a
     * similar one exists.
     */
    public function rules(): array
    {
        return [
            'material_category_id' => ['required', 'integer', $this->categoryRule()],
            'base_name' => ['required', 'string', 'max:150'],
            'spec' => ['nullable', 'string', 'max:150'],
            'brand' => ['nullable', 'string', 'max:100'],
            'unit_id' => ['required', 'integer', new SelectableUnit($this->currentUnitIds())],
            'cost_price' => ['required', 'numeric', 'min:0', 'max:9999999999'],
            'sell_price' => ['required', 'numeric', 'min:0', 'max:9999999999'],
            'min_stock' => ['required', 'numeric', 'decimal:0,2', 'min:0', 'max:999999999'],
            'similar_reason' => ['nullable', 'string', 'max:500'],
        ];
    }

    /** @return list<int> Units the edited material already uses — none when creating. */
    protected function currentUnitIds(): array
    {
        return [];
    }

    /** New items take an active category; an edit may keep its current one. */
    protected function categoryRule(): mixed
    {
        return Rule::exists('material_categories', 'id')->where('is_active', true);
    }

    public function messages(): array
    {
        return [
            'material_category_id.required' => 'Kategori wajib dipilih.',
            'material_category_id.exists' => 'Kategori tidak ditemukan atau sudah nonaktif.',
            'base_name.required' => 'Nama dasar barang wajib diisi.',
            'unit_id.required' => 'Satuan wajib dipilih.',
            'cost_price.required' => 'Harga modal wajib diisi.',
            'sell_price.required' => 'Harga jual wajib diisi.',
            'min_stock.required' => 'Stok minimum wajib diisi.',
            'min_stock.decimal' => 'Stok minimum maksimal 2 angka di belakang koma.',
        ];
    }
}
